spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:h2:mem:los_master_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

master:
  datasource:
    url: "jdbc:h2:mem:los_master_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

bank:
  datasource:
    driver-class-name: org.h2.Driver
    default-url-prefix: "jdbc:h2:mem:"
    default-url-suffix: ";DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"
    username: sa
    password: ""

tenant:
  datasource:
    driver-class-name: org.h2.Driver
    default-url-prefix: "jdbc:h2:mem:"
    default-url-suffix: ";DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"
    username: sa
    password: ""

organization:
  datasource:
    driver-class-name: org.h2.Driver
    default-url-prefix: "jdbc:h2:mem:"
    default-url-suffix: ";DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"
    username: sa
    password: ""

