spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

master:
  datasource:
    url: ${MASTER_DB_URL:jdbc:postgresql://localhost:5432/los_master_db}
    username: ${MASTER_DB_USERNAME:postgres}
    password: ${MASTER_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

tenant:
  datasource:
    driver-class-name: org.postgresql.Driver
    default-host: ${TENANT_DB_HOST:localhost}
    default-port: ${TENANT_DB_PORT:5432}
    username: ${TENANT_DB_USERNAME:postgres}
    password: ${TENANT_DB_PASSWORD:postgres}
